# Generated by Django 5.0.6 on 2026-06-11 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('fuente_datos', models.CharField(default='dataset_clinico_etl_1800_registros.xlsx', help_text='Nombre del archivo o URL de origen', max_length=255)),
                ('registros_leidos', models.PositiveIntegerField(default=0)),
                ('registros_duplicados', models.PositiveIntegerField(default=0)),
                ('registros_invalidos', models.PositiveIntegerField(default=0)),
                ('registros_cargados', models.PositiveIntegerField(default=0)),
                ('tiempo_ejecucion_seg', models.DecimalField(decimal_places=3, default=0, help_text='Tiempo total de ejecución en segundos', max_digits=8)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('parcial', 'Parcial')], default='exitoso', max_length=10)),
                ('mensaje_error', models.TextField(blank=True, default='')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que disparó el proceso ETL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log ETL',
                'verbose_name_plural': 'Logs ETL',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
    ]
