# Generated by Django 5.0.6 on 2026-05-27 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('edad', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120)])),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, help_text='Altura en metros', max_digits=3)),
                ('glucosa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colesterol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('presion_sistolica', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(250)])),
                ('antecedentes_familiares', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
