# Generated by Django 6.0.5 on 2026-05-27 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='actividad_fisica',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='frecuencia_cardiaca',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)]),
        ),
        migrations.AddField(
            model_name='patient',
            name='presion_diastolica',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
