# Generated by Django 6.0.5 on 2026-05-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0002_patient_actividad_fisica_patient_frecuencia_cardiaca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consumo_alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnostico_preliminar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fumador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='riesgo_enfermedad',
            field=models.CharField(default='Bajo', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='saturacion_oxigeno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
