# Generated by Django 6.0.5 on 2026-05-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0003_patient_consumo_alcohol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diagnostico_preliminar',
            field=models.CharField(blank=True, help_text='Diagnóstico inicial dado por el médico', max_length=100, null=True),
        ),
    ]
