# Generated by Django 6.0.5 on 2026-05-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0004_alter_patient_diagnostico_preliminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='colesterol',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnostico_preliminar',
            field=models.CharField(default='Sin Diagnóstico', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='edad',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='frecuencia_cardiaca',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='glucosa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='presion_diastolica',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='presion_sistolica',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='saturacion_oxigeno',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
