# Generated by Django 5.0.6 on 2026-06-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_records', '0006_patient_imc_patient_fecha_consulta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='colesterol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='edad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='frecuencia_cardiaca',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='glucosa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='presion_diastolica',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='presion_sistolica',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='saturacion_oxigeno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['riesgo_enfermedad'], name='clinical_re_riesgo__4fe54d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['diagnostico_preliminar'], name='clinical_re_diagnos_bb7f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['fecha_consulta'], name='clinical_re_fecha_c_9f01eb_idx'),
        ),
    ]
